refactor(LambdaClouddriverUtils/UnitTests): Add some unit tests to LambdaClouddriverUtils
spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker pull request #94
Opened 2021-07-30 15:13 UTC by jorgebee65

Add some unit tests to LambdaClouddriverUtils

2021-07-30 17:39 UTC, zachsmith1 commented
@jorgebee65 Please add tests that cover methods with logic in them. In this case, we want to try and cover methods that have multiple paths of completion. I was hoping to see statement, path, and branch coverage if possible. To get an idea of these concepts at a high level, please check out this link: https://sites.google.com/site/swtestingconcepts/home/test-design-techniques/for-white-box/statement-branch-and-path-coverage

2021-08-05 23:10 UTC, zachsmith1 requested changes

2021-08-31 21:13 UTC, jorgebee65 commented on lambda-deployment-orca/src/test/java/com/amazon/aws/spinnaker/plugin/lambda/utils/LambdaClouddriverUtilsTest.java
> +    private OortService oortMock;
OortService was removed

2021-09-02 15:38 UTC, zachsmith1 approved these changes

2021-09-02 15:40 UTC, merged